### ISSUE TITLE
custom metrics paths

### ISSUE THREAD

**Issue by marksawers** [teralytics/prometheus-ecs-discovery#14]
Use of the docker label PROMETHEUS_EXPORTER_PORT on ecs tasks implies the tool is oriented to discovering exporter tasks. Presumably the path is the standard host:port/metrics.

Can it also discover application scrapper endpoints on custom paths? My web services incorporate micrometer (via spring boot actuator framework) to publish prometheus scrapper endpoints on their regular operational ports, but at the path  {service-name}/management/prometheus. Is there a mechanism in the discovery tool to customize the prometheus metrics_path?

**Comment by tomotway** [comment]
Hi, I had the same issue and have just created PROMETHEUS_EXPORTER_PATH under https://github.com/teralytics/prometheus-ecs-discovery/pull/16 

The code seems to work but I'm new to this stuff so, if you use it, please test thoroughly

**Comment by marksawers** [comment]
Schaweet! Thank you for that.

**Comment by chicofranchico** [comment]
Thanks for that!
