### ISSUE TITLE
[Feature request]: Scrape from dynamic ports

### ISSUE THREAD

**Issue by dskarataev** [teralytics/prometheus-ecs-discovery#38]
We are using dynamic ports for ECS, having more than one instance of the app on the same EC2 (not mandatory but it is possible and depends on the autoscaling group).

Could you please add a feature to be able to somehow discover on what port the application is running and do not type the port statically inside the Docker Label?

Thank you!

**Comment by tgolly** [comment]
Have you tried https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-discovery.html to create Route 53 "SRV" DNS records each time a container is created?

Prometheus can then discovery the containers (and ports) via a "dns_sd_configs" scrape job.

**Comment by dgrizzanti** [comment]
The downside to using SRV records with Route53 is that you only get back up to 8 healthy IPs, selected at random.

https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-policy.html#routing-policy-multivalue

**Comment by dcelasun** [comment]
I've opened a PR with a working implementation. Feedback is welcome.
