### ISSUE TITLE
Getting ECS cluster (instance/container) metrics into the prometheus dashbord

### ISSUE THREAD

**Issue by thisara-noetic** [teralytics/prometheus-ecs-discovery#44]
Hi,

I just got able to build the "prometheus-ecs-discovery" container by using the "teralytics/prometheus-ecs-discovery" code. I have given necessary AWS credentials, once I run the docker image.

Eg:

> docker run -idt --name ecs-discovery -e AWS_REGION=eu-west-1 -e AWS_ACCESS_KEY_ID=XXXXXXXXXX -e AWS_SECRET_ACCESS_KEY=XXXXXXXXXXXXX ecs-discovery

And I got able to successfully start the container and I got able to ssh into the container also.
Then once I run the "prometheus-ecs-discovery" inside the container, It has shown all the cluster details list.

I have gone through the many online documents to get the cluster instance/container metrics into the Prometheus dashbord, but I haven't been able to find a proper way to get the cluster instance/container metrics into the prometheus dashbord as a prometheus target.

Please support me to achieve this target.

Thanks

**Comment by chicofranchico** [comment]
Make sure the generated file is readable by the master and that you reload the master's config.

**Comment by thisara-noetic** [comment]
You mean "ecs_file_sd.yml" ..?
Unfortunately it shows "**Writing 0 discovered exporters to /tmp/ecs_file_sd.yml**"
That file is having 777 permission, but nothing has written in it.

Could you please help me for it..?

**Comment by chicofranchico** [comment]
You asked the same thing on #8. Can you paste your task definition?

**Comment by thisara-noetic** [comment]
Hi,
Below is my task definition JSON content.

> {
  "ipcMode": null,
  "executionRoleArn": "arn:aws:iam::11111111111111:role/ecsTaskExecutionRole",
  "containerDefinitions": [
    {
      "dnsSearchDomains": null,
      "logConfiguration": {
        "logDriver": "gelf",
        "secretOptions": null,
        "options": {
          "gelf-address": "udp://graylog.xxx.com:19211"
        }
      },
      "entryPoint": null,
      "portMappings": [
        {
          "hostPort": 9222,
          "protocol": "tcp",
          "containerPort": 9222
        }
      ],
      "command": null,
      "linuxParameters": null,
      "cpu": 512,
      "environment": [],
      "resourceRequirements": null,
      "ulimits": null,
      "dnsServers": null,
      "mountPoints": [],
      "workingDirectory": "/tmp/",
      "secrets": null,
      "dockerSecurityOptions": null,
      "memory": 500,
      "memoryReservation": null,
      "volumesFrom": [],
      "stopTimeout": null,
      "image": "111111111111.dkr.ecr.eu-west-1.amazonaws.com/ecs-discovery:latest",
      "startTimeout": null,
      "dependsOn": null,
      "disableNetworking": null,
      "interactive": null,
      "healthCheck": null,
      "essential": true,
      "links": null,
      "hostname": null,
      "extraHosts": null,
      "pseudoTerminal": null,
      "user": null,
      "readonlyRootFilesystem": null,
      "dockerLabels": null,
      "systemControls": null,
      "privileged": null,
      "name": "ecsdiscovery"
    }
  ],
  "placementConstraints": [],
  "memory": "512",
  "taskRoleArn": "arn:aws:iam::111111111111:role/ecsTaskExecutionRole",
  "compatibilities": [
    "EC2"
  ],
  "taskDefinitionArn": "arn:aws:ecs:eu-west-1:111111111111:task-definition/ecs-discovery:3",
  "family": "ecs-discovery",
  "requiresAttributes": [
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.ecr-auth"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.19"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.17"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.task-iam-role"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.logging-driver.gelf"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "ecs.capability.execution-role-ecr-pull"
    }
  ],
  "pidMode": null,
  "requiresCompatibilities": [
    "EC2"
  ],
  "networkMode": "bridge",
  "cpu": null,
  "revision": 3,
  "status": "ACTIVE",
  "inferenceAccelerators": null,
  "proxyConfiguration": null,
  "volumes": []
}


Hope this is fine.

Thanks

**Comment by chicofranchico** [comment]
you haven't specified any dockerLabels. Please read the README carefully

**Comment by thisara-noetic** [comment]
Hi,
I have already gone through the README. But I thing I still didn't understand exact work flow that how this is going to work. 

Let me explain the way I did,
1. I configured the current EC2 server (which runs the "teralytics/prometheus-ecs-discovery" docker container ) to access the required AWS account, by using "aws configure" .
2. Then I Downloaded the "prometheus-ecs-discovery" from github.
3. Build the docker image. (docker build -t ecs-discovery .)
4. Started the container.

> docker run -idt --name ecs-discovery -e AWS_REGION=eu-west-1 -e AWS_ACCESS_KEY_ID=XXXXXXXXXX -e AWS_SECRET_ACCESS_KEY=XXXXXXXXXXXXX ecs-discovery

Then once I logged into the "ecs-discovery" container, I run the following command ,

> prometheus-ecs-discovery -config.scrape-interval 5s -config.write-to /tmp/ecs_file_sd.yml -config.port-label 9222

And I got the following output in every 5 seconds.

> / # prometheus-ecs-discovery -config.scrape-interval 5s -config.write-to /tmp/ecs_file_sd.yml -config.port-label 9222
2019/08/28 05:09:56 Inspected cluster arn:aws:ecs:eu-west-1:111111111111:cluster/preprod-api-cluster, found 15 tasks
2019/08/28 05:09:56 Inspected cluster arn:aws:ecs:eu-west-1:111111111111:cluster/preprod-frontend-cluster, found 16 tasks
2019/08/28 05:09:56 Inspected cluster arn:aws:ecs:eu-west-1:111111111111:cluster/fe-production-cluster, found 1 tasks
2019/08/28 05:09:56 Inspected cluster arn:aws:ecs:eu-west-1:111111111111:cluster/CRO-production-cluster, found 1 tasks
2019/08/28 05:09:56 Described 1 tasks in cluster arn:aws:ecs:eu-west-1:111111111111:cluster/fe-production-cluster
2019/08/28 05:09:56 Inspected cluster arn:aws:ecs:eu-west-1:111111111111:cluster/production-api-cluster, found 4 tasks
2019/08/28 05:09:56 Described 1 tasks in cluster arn:aws:ecs:eu-west-1:111111111111:cluster/CRO-production-cluster
2019/08/28 05:09:56 Inspected cluster arn:aws:ecs:eu-west-1:111111111111:cluster/production-saas-cluster, found 4 tasks
2019/08/28 05:09:56 Described 16 tasks in cluster arn:aws:ecs:eu-west-1:111111111111:cluster/preprod-frontend-cluster
2019/08/28 05:09:56 Described 4 tasks in cluster arn:aws:ecs:eu-west-1:111111111111:cluster/production-api-cluster
2019/08/28 05:09:56 Described 15 tasks in cluster arn:aws:ecs:eu-west-1:111111111111:cluster/preprod-api-cluster
2019/08/28 05:09:56 Inspected cluster arn:aws:ecs:eu-west-1:111111111111:cluster/production-saas-cluster-natted, found 1 tasks
2019/08/28 05:09:56 Inspected cluster arn:aws:ecs:eu-west-1:111111111111:cluster/preprod-saas-cluster, found 15 tasks
2019/08/28 05:09:56 Inspected cluster arn:aws:ecs:eu-west-1:111111111111:cluster/testing-cluster, found 2 tasks
2019/08/28 05:09:56 Described 4 tasks in cluster arn:aws:ecs:eu-west-1:111111111111:cluster/production-saas-cluster
2019/08/28 05:09:56 Described 1 tasks in cluster arn:aws:ecs:eu-west-1:111111111111:cluster/production-saas-cluster-natted
2019/08/28 05:09:56 Described 2 tasks in cluster arn:aws:ecs:eu-west-1:111111111111:cluster/testing-cluster
2019/08/28 05:09:56 Described 15 tasks in cluster arn:aws:ecs:eu-west-1:111111111111:cluster/preprod-saas-cluster
2019/08/28 05:09:56 Described 21 EC2 reservations
2019/08/28 05:09:56 Writing 0 discovered exporters to /tmp/ecs_file_sd.yml

As you can see, the output shows all the clusters.
I know I have missed some steps to make this solution work, but I have no idea where and what I have missed.
It's really appreciated if you can provide some work-flow to get this success.

Thanks.

**Comment by chicofranchico** [comment]
You're missing the dockerLabel definitions

**Comment by thisara-noetic** [comment]
Hi,
I have recreated the cluster and task definition and run the service again.
Below is the task definition.
Hope this is Okay.

> {
  "ipcMode": null,
  "executionRoleArn": "arn:aws:iam::111111111111:role/ecsTaskExecutionRole",
  "containerDefinitions": [
    {
      "dnsSearchDomains": null,
      "logConfiguration": null,
      "entryPoint": null,
      "portMappings": [
        {
          "hostPort": 5222,
          "protocol": "tcp",
          "containerPort": 5222
        }
      ],
      "command": null,
      "linuxParameters": null,
      "cpu": 0,
      "environment": [],
      "resourceRequirements": null,
      "ulimits": null,
      "dnsServers": null,
      "mountPoints": [],
      "workingDirectory": null,
      "secrets": null,
      "dockerSecurityOptions": null,
      "memory": 512,
      "memoryReservation": null,
      "volumesFrom": [],
      "stopTimeout": null,
      "image": "111111111111.dkr.ecr.eu-west-1.amazonaws.com/ecs-discovery",
      "startTimeout": null,
      "dependsOn": null,
      "disableNetworking": null,
      "interactive": null,
      "healthCheck": null,
      "essential": true,
      "links": null,
      "hostname": null,
      "extraHosts": null,
      "pseudoTerminal": null,
      "user": null,
      "readonlyRootFilesystem": null,
      "dockerLabels": {
        "PROMETHEUS_EXPORTER_PORT": "5222"
      },
      "systemControls": null,
      "privileged": null,
      "name": "ecs-discovery-container"
    }
  ],
  "placementConstraints": [],
  "memory": "512",
  "taskRoleArn": "arn:aws:iam::111111111111:role/ecsTaskExecutionRole",
  "compatibilities": [
    "EC2"
  ],
  "taskDefinitionArn": "arn:aws:ecs:eu-west-1:111111111111:task-definition/ecs-discovery-td:1",
  "family": "ecs-discovery-td",
  "requiresAttributes": [
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.ecr-auth"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.task-iam-role"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "ecs.capability.execution-role-ecr-pull"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.18"
    }
  ],
  "pidMode": null,
  "requiresCompatibilities": [
    "EC2"
  ],
  "networkMode": "bridge",
  "cpu": "512",
  "revision": 1,
  "status": "ACTIVE",
  "inferenceAccelerators": null,
  "proxyConfiguration": null,
  "volumes": []
}

Thanks.

**Comment by thisara-noetic** [comment]
Hi there,

Thanks for your support.
I got able to successfully configure the task-definitions and run it as a service in two clusters initially.
And  now the "ecs_file_sd.yml" file also getting updated.

> - targets:
  - 172.33.29.23:5222
  labels:
    task_arn: arn:aws:ecs:eu-west-1:111111111111:task/e58ca7ae-2914-401e-8688-3050ff971d33
    task_name: ecs-discovery-td
    task_revision: "1"
    task_group: service:ecs-discovery-service-PP-FE
    cluster_arn: arn:aws:ecs:eu-west-1:111111111111:cluster/preprod-frontend-cluster
    container_name: ecs-discovery-container
    container_arn: arn:aws:ecs:eu-west-1:111111111111:container/930831f2-5f94-4001-a021-b953a0d23f9e
    docker_image: 111111111111.dkr.ecr.eu-west-1.amazonaws.com/ecs-discovery
- targets:
  - 10.0.1.75:5222
  labels:
    task_arn: arn:aws:ecs:eu-west-1:111111111111:task/e8ce0477-8760-480c-8e67-0ea857bbd932
    task_name: ecs-discovery-td
    task_revision: "1"
    task_group: service:ecs-discovery-service
    cluster_arn: arn:aws:ecs:eu-west-1:111111111111:cluster/ecs-discovery-cluster
    container_name: ecs-discovery-container
    container_arn: arn:aws:ecs:eu-west-1:111111111111:container/136f2578-f83c-4ee4-9c44-1b3fcf64c9d6
    docker_image: 111111111111.dkr.ecr.eu-west-1.amazonaws.com/ecs-discovery

And I  have configured the prometheus.yml file in prometheus server as follows.

> .........
  - job_name: 'ecs'
    file_sd_configs:
      - files:
        - /etc/prometheus/ecs_file_sd.yml
        refresh_interval: 5s
    metric_relabel_configs:
      - regex: task_arn
        action: labeldrop

...........

And once I check the prometheus targets, both the endpoints were down.

![image](https://user-images.githubusercontent.com/54018114/64015344-f8dc2300-cb41-11e9-9e78-aaab88a8e43c.png)


Is there something wrong/missing with the configs with "prometheus.yml" file..?


Thanks

**Comment by chicofranchico** [comment]
There's nothing wrong with the generated files (since they ended up in your prometheus). It's either a connectivity issue (your master can't reach that port) or the exporter is not running.
