### ISSUE TITLE
Error when fetching data for Fargate task

### ISSUE THREAD

**Issue by nemo83** [teralytics/prometheus-ecs-discovery#5]
Hi!

First of all thanks for filling the gap prometheus has with ECS.

In work we are trialling Fargate as way to release to production but of course we can't do w/o monitoring.

I just tried your code via `https://hub.docker.com/r/mthenw/prometheus-ecs-discovery/~/dockerfile/`

But when I try to run it, it crashes when fetching data for Fargate taks/services
```
2017/12/16 20:32:53 Described task definition arn:aws:ecs:us-east-1:1234567890:task-definition/web-xxx-xxxx:5
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6f5261]

goroutine 1 [running]:
main.AddContainerInstancesToTasks(0xc4200800a8, 0xc4200800b8, 0xc420196500, 0xf, 0x10, 0xf, 0x10, 0x0, 0x0, 0x0)
	/go/src/github.com/teralytics/prometheus-ecs-discovery/main.go:304 +0x1a1
main.GetAugmentedTasks(0xc4200800a8, 0xc4200800b8, 0xc42017e1b0, 0x6, 0x6, 0x2, 0x2, 0xc420115f6c, 0x2, 0x2)
	/go/src/github.com/teralytics/prometheus-ecs-discovery/main.go:455 +0x309
main.main.func1()
	/go/src/github.com/teralytics/prometheus-ecs-discovery/main.go:474 +0xa3
main.main()
	/go/src/github.com/teralytics/prometheus-ecs-discovery/main.go:504 +0x212
```

Can you help?

Thanks in advance.

**Comment by lukanus** [comment]
Hey! 
I've opened PR for that just now  #10  
So maybe it'll help you, If you're still interested. 

Cheers 
Ł

**Comment by chicofranchico** [comment]
Merged the PR. If it helps, could you close this issue? Thanks!

**Comment by nemo83** [comment]
Great stuff guys!! 

Thanks @lukanus for the PR and @chicofranchico for merging it!
