### ISSUE TITLE
Question: Do you need service discovery enabled on the ECS tasks for this to work?

### ISSUE THREAD

**Issue by rmccarthy-ellevation** [teralytics/prometheus-ecs-discovery#58]
Question: Do you need service discovery enabled on the ECS tasks for this to work or does it use the API to get around the use of service discovery?

**Comment by Rudd-O** [comment]
This code scrapes the AWS API for that information:

```
var interval = flag.Duration("config.scrape-interval", 60*time.Second, "interval at which to scrape the AWS API for ECS service discovery information")
```

Read `main.go` for more information :-)
